input: input.cpp
	g++ -std=c++20 input.cpp -o input

linux_keyboard_testrun: linux_keyboard_testrun.cpp ../core/input/input.h ../core/input/drivers/linux_keyboard.h ../core/input/drivers/linux_keyboard.cpp
	g++ -std=c++20 linux_keyboard_testrun.cpp ../core/input/drivers/linux_keyboard.cpp -o linux_keyboard_testrun
