input: input.cpp
	g++ -std=c++20 input.cpp -o input

linux_keyboard_testrun: linux_keyboard_testrun.cpp ../core/engine.cpp ../core/input/input.cpp ../core/input/drivers/linux_keyboard.cpp
	g++ -std=c++20 -g linux_keyboard_testrun.cpp ../core/engine.cpp ../core/input/input.cpp ../core/input/drivers/linux_keyboard.cpp -o linux_keyboard_testrun
